//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dipstick.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIPSTICK_DIALOG             102
#define IDS_REGEX_NESTEDURL             102
#define IDS_PS_FAILEDTOLOCK             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_REGEX_CRACKHOST             104
#define IDS_CSVEXT                      104
#define IDS_HN_BADURL                   105
#define IDS_ABEST_CLEANUP               106
#define IDS_ABEST_NONEFOUND             107
#define IDS_ABEST_TITLE                 108
#define IDS_DRAGPAD_TITLE               109
#define IDS_DRAGPAD_URLS                110
#define IDS_REGEX_HTMLURL               111
#define IDS_CSVFILTER                   112
#define IDS_REGEX_URL                   113
#define IDR_MAINFRAME                   128
#define IDD_DRAGPAD                     129
#define IDR_DNDAVI                      130
#define IDD_OPTIONS                     132
#define IDR_MENU                        133
#define IDD_MANUALHOST                  134
#define IDD_PROPS                       135
#define IDI_PINGING                     136
#define IDI_PENDING                     137
#define IDI_COMPLETED                   138
#define IDI_UNREACHABLE                 139
#define IDB_DIABACK                     140
#define IDD_AUTOBEST                    141
#define IDW_BESTURL                     142
#define IDR_DRAGAVI                     143
#define IDD_URLS                        145
#define IDC_HOSTLIST                    1002
#define IDC_DNDTARGET                   1011
#define IDC_OPTIONS                     1013
#define IDC_NPINGS                      1014
#define IDC_PACKETSIZE                  1015
#define IDC_TIMEOUT                     1016
#define IDC_INTERVAL                    1017
#define IDC_KLEVERNET                   1017
#define IDC_MAXPINGS                    1018
#define IDC_MANUALPING                  1019
#define IDC_HOST                        1020
#define IDC_REPING                      1021
#define IDC_IP                          1021
#define IDC_REPINGALL                   1022
#define IDC_CLEAR                       1023
#define IDC_EXIT                        1024
#define IDC_REMOVE                      1025
#define IDC_URLCAPTION                  1026
#define IDC_URL                         1027
#define IDC_HOSTCAPTION                 1028
#define IDC_IPCAPTION                   1029
#define IDC_TIMESCAPTION                1030
#define IDC_TIMES                       1031
#define IDC_LOSSCAPTION                 1032
#define IDC_LOSS                        1033
#define IDC_STATUSCAPTION               1034
#define IDC_STATUS                      1035
#define IDC_OPENURL                     1036
#define IDC_STATE                       1039
#define IDC_MSWORKAROUND                1048
#define IDC_SPINPINGS                   1049
#define IDC_SPINMAXPINGS                1050
#define IDC_SPINTIMEOUT                 1051
#define IDC_RTT                         1051
#define IDC_SPINTERVAL                  1052
#define IDC_PKTLOSS                     1052
#define IDC_SPINSIZE                    1053
#define IDC_PREV                        1053
#define IDC_AUTOBEST                    1054
#define IDC_NEXT                        1054
#define IDC_SMARTADJUST                 1055
#define IDC_DROPSOURCE                  1056
#define IDC_URLS                        1057
#define IDC_DOADJUST                    1058
#define IDC_ADJUSTINN                   1059
#define IDC_IGNORELA                    1060
#define IDC_COPYURL                     1060
#define IDC_ADVANCED                    1061
#define IDS_KLEVERNET_URL               2102
#define IDS_PS_INTERNALERROR            2104
#define IDS_PS_NETUNREACHABLE           2105
#define IDS_PS_HOSTUNREACHABLE          2106
#define IDS_PS_PROTUNREACHABLE          2107
#define IDS_PS_PORTUNREACHABLE          2108
#define IDS_PS_NORESOURCES              2109
#define IDS_PS_HWERROR                  2110
#define IDS_PS_BIGPACKET                2111
#define IDS_PS_TIMEOUT                  2112
#define IDS_PS_BADROUTE                 2113
#define IDS_PS_TTLEXPTRANSIT            2114
#define IDS_PS_TTLEXPREASM              2115
#define IDS_PS_IPARAMP                  2116
#define IDS_PS_SOURCEQUENCH             2117
#define IDS_PS_BIGOPTION                2118
#define IDS_PS_BADDEST                  2119
#define IDS_PS_UNKNOWNERROR             2120
#define IDS_REGISTRYKEY                 2121
#define IDS_FMT_TIMES                   2122
#define IDS_FMT_LOSS                    2123
#define IDS_TIP_UNREACHABLE             2124
#define IDS_PS_FAILEDTORESOLVE          2127
#define IDS_PS_UNABLETOICMP             2128
#define IDS_TIP_PENDING                 2130
#define IDS_TIP_COMPLETE                2131
#define IDS_TIP_PROPSOK                 2132
#define IDS_TIP_INTERVAL                2133
#define IDS_TIP_OPTIONSOK               2134
#define IDS_TIP_OPTIONSCANCEL           2135
#define IDS_TIP_PINGING                 2136
#define ID_DRAGPAD_EXIT                 32771
#define ID_DRAGPAD_SHOWMAINWINDOW       32772
#define ID_DRAGPAD_OPTIONS              32773
#define ID_DRAGPAD_ABOUT                32774
#define ID_DRAGPAD_MANUALPING           32775
#define ID_HOSTLIST_REPING              32776
#define ID_HOSTLIST_REMOVE              32777
#define ID_HOSTLIST_REPINGALL           32778
#define ID_HOSTLIST_REMOVEALL           32779
#define ID_HOSTLIST_OPENURL             32780
#define ID_HOSTLIST_PROPERTIES          32781
#define ID_DRAGPAD_HELP                 32782
#define ID_DRAGPAD_REPINGALL            32783
#define ID_DRAGPAD_REMOVEALL            32784
#define ID_DRAGPAD_PASTEURL             32785
#define ID_HOSTLIST_PASTEURL            32786
#define ID_HOSTLIST_COPYURL             32787
#define ID_ADVANCED_EXPORTLIST          32788
#define ID_ADVANCED_IMPORTLIST          32789
#define ID_DRAGPAD_ADVANCED_EXPORTLIST  32790
#define ID_DRAGPAD_ADVANCED_IMPORTLIST  32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
